/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package irrgartenUI;

import irrgartenGame.GameState;
import irrgartenGame.Directions;
import java.awt.Font;

/**
 * Implementación gráfica de {@link UI} utilizando {@link javax.swing.JFrame}.
 * 
 * Esta clase muestra el estado del juego en una ventana Swing, mostrando:
 * <ul>
 *   <li>El laberinto ({@link #TextLabyrinth})</li>
 *   <li>Jugadores ({@link #TextPlayers})</li>
 *   <li>Monstruos ({@link #TextMonsters})</li>
 *   <li>Registro de eventos ({@link #TextLog})</li>
 *   <li>Jugador actual ({@link #ActualLabel})</li>
 *   <li>Si hay ganador ({@link #WinnerLabel})</li>
 * </ul>
 * 
 * La dirección de movimiento del usuario se obtiene mediante la clase {@link Cursors}.
 * 
 * @author asier
 */
public class GraphicalUI extends javax.swing.JFrame implements UI {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GraphicalUI.class.getName());
    
    /** Gestiona la entrada del usuario para seleccionar la dirección de movimiento 
     *  {@link Cursors}
     */
    private Cursors cursors;

    /**
     * Crea una nueva interfaz gráfica y la inicializa.
     * Configura los componentes Swing y la fuente de {@link #TextLabyrinth}.
     */
    public GraphicalUI() {
        this.cursors = new Cursors(this,true);
        initComponents();
        TextLabyrinth.setFont(new Font("Monospaced", Font.PLAIN, 23));
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextLabyrinth = new javax.swing.JTextArea();
        CurrentPlayerLabel = new javax.swing.JLabel();
        HaveAWinner = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextLog = new javax.swing.JTextField();
        Titulo = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TextMonsters = new javax.swing.JTextArea();
        ActualLabel = new javax.swing.JLabel();
        WinnerLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextPlayers = new javax.swing.JTextArea();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextLabyrinth.setEditable(false);
        TextLabyrinth.setColumns(20);
        TextLabyrinth.setLineWrap(true);
        TextLabyrinth.setRows(5);
        TextLabyrinth.setWrapStyleWord(true);
        TextLabyrinth.setAutoscrolls(false);
        TextLabyrinth.setBorder(new javax.swing.border.MatteBorder(null));
        TextLabyrinth.setFocusable(false);
        jScrollPane1.setViewportView(TextLabyrinth);

        CurrentPlayerLabel.setFont(new java.awt.Font("Linux Libertine Mono O", 3, 24)); // NOI18N
        CurrentPlayerLabel.setText("Jugador actual : ");
        CurrentPlayerLabel.setFocusable(false);

        HaveAWinner.setFont(new java.awt.Font("Linux Libertine Mono O", 3, 24)); // NOI18N
        HaveAWinner.setText("Ganador? ");
        HaveAWinner.setFocusable(false);

        jLabel3.setFont(new java.awt.Font("Linux Libertine O", 3, 15)); // NOI18N
        jLabel3.setText("Log:");

        jLabel4.setFont(new java.awt.Font("Linux Biolinum O", 3, 15)); // NOI18N
        jLabel4.setText("Jugadores:");
        jLabel4.setFocusable(false);

        jLabel5.setFont(new java.awt.Font("Linux Libertine O", 3, 15)); // NOI18N
        jLabel5.setText("Monstruos:");
        jLabel5.setFocusable(false);

        TextLog.setEditable(false);
        TextLog.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        TextLog.setText("jTextField1");
        TextLog.setFocusable(false);
        TextLog.addActionListener(this::TextLogActionPerformed);

        Titulo.setFont(new java.awt.Font("Linux Libertine Mono O", 3, 36)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Irrgarten");

        TextMonsters.setEditable(false);
        TextMonsters.setColumns(20);
        TextMonsters.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        TextMonsters.setRows(5);
        jScrollPane4.setViewportView(TextMonsters);

        ActualLabel.setFont(new java.awt.Font("Linux Biolinum O", 2, 24)); // NOI18N
        ActualLabel.setText("jLabel1");

        WinnerLabel.setFont(new java.awt.Font("Linux Biolinum O", 2, 24)); // NOI18N
        WinnerLabel.setText("jLabel1");

        TextPlayers.setEditable(false);
        TextPlayers.setColumns(20);
        TextPlayers.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        TextPlayers.setRows(5);
        jScrollPane2.setViewportView(TextPlayers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(127, 127, 127)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CurrentPlayerLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ActualLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(HaveAWinner)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(WinnerLabel)))
                        .addGap(150, 150, 150))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(39, 39, 39)
                        .addComponent(TextLog, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CurrentPlayerLabel)
                            .addComponent(ActualLabel))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HaveAWinner)
                            .addComponent(WinnerLabel)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextLogActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new GraphicalUI().setVisible(true));
//    }

    /**
     * Muestra el estado del juego en la interfaz gráfica.
     * 
     * Actualiza los componentes:
     * {@link #TextMonsters}, {@link #TextPlayers}, {@link #TextLog}, {@link #TextLabyrinth},
     * {@link #ActualLabel} y {@link #WinnerLabel}.
     *
     * @param gameState el {@link GameState} que contiene la información actual del juego
     */
    @Override
    public void showGame(GameState gameState) {   
        TextMonsters.setText(gameState.getMonsters());
        TextPlayers.setText(gameState.getPlayers());
        TextLog.setText(gameState.getLog());
        TextLabyrinth.setText(gameState.getLabyrinth());
        
        ActualLabel.setText(Integer.toString(gameState.getCurrentPlayer()));
        WinnerLabel.setText(winnerLabel(gameState.isWinner()));
        
        repaint();
    }

    
    /**
     * Convierte un valor booleano en una cadena para la etiqueta de ganador.
     * 
     * @param winner true si hay ganador, false si no
     * @return "Si" si winner es true, "No" en caso contrario
     */
    private String winnerLabel(boolean winner){
        return winner ? "Si" : "No";
    }

    /**
     * Devuelve la dirección de movimiento seleccionada por el usuario
     * mediante la clase {@link Cursors}.
     * 
     * @return {@link Directions} elegida por el usuario
     */
    @Override
    public Directions nextMove() {
        return this.cursors.getDirection();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ActualLabel;
    private javax.swing.JLabel CurrentPlayerLabel;
    private javax.swing.JLabel HaveAWinner;
    private javax.swing.JTextArea TextLabyrinth;
    private javax.swing.JTextField TextLog;
    private javax.swing.JTextArea TextMonsters;
    private javax.swing.JTextArea TextPlayers;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel WinnerLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
