/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package irrgartenUI;

import irrgartenGame.GameState;
import irrgartenGame.Directions;


/**
 *
 * @author asier
 */
public class GraphicalUI extends javax.swing.JFrame implements UI {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GraphicalUI.class.getName());
    private Cursors cursors;
    /**
     * Creates new form GraphicalUI
     */
    public GraphicalUI() {
        this.cursors = new Cursors(this,true);
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextLabyrinth = new javax.swing.JTextArea();
        CurrentPlayerLabel = new javax.swing.JLabel();
        HaveAWinner = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextLog = new javax.swing.JTextField();
        Titulo = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextPlayers = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        TextMonsters = new javax.swing.JTextArea();
        ActualLabel = new javax.swing.JLabel();
        WinnerLabel = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextLabyrinth.setEditable(false);
        TextLabyrinth.setColumns(20);
        TextLabyrinth.setRows(5);
        TextLabyrinth.setFocusable(false);
        jScrollPane1.setViewportView(TextLabyrinth);

        CurrentPlayerLabel.setFont(new java.awt.Font("Linux Libertine Mono O", 3, 24)); // NOI18N
        CurrentPlayerLabel.setText("Jugador actual : ");
        CurrentPlayerLabel.setFocusable(false);

        HaveAWinner.setFont(new java.awt.Font("Linux Libertine Mono O", 3, 24)); // NOI18N
        HaveAWinner.setText("Ganador? ");
        HaveAWinner.setFocusable(false);

        jLabel3.setFont(new java.awt.Font("Linux Libertine O", 3, 15)); // NOI18N
        jLabel3.setText("Log:");

        jLabel4.setFont(new java.awt.Font("Linux Biolinum O", 3, 15)); // NOI18N
        jLabel4.setText("Jugadores:");
        jLabel4.setFocusable(false);

        jLabel5.setFont(new java.awt.Font("Linux Libertine O", 3, 15)); // NOI18N
        jLabel5.setText("Monstruos:");
        jLabel5.setFocusable(false);

        TextLog.setEditable(false);
        TextLog.setText("jTextField1");
        TextLog.setFocusable(false);
        TextLog.addActionListener(this::TextLogActionPerformed);

        Titulo.setFont(new java.awt.Font("Linux Libertine Mono O", 3, 36)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Irrgarten");

        TextPlayers.setEditable(false);
        TextPlayers.setColumns(20);
        TextPlayers.setRows(5);
        TextPlayers.setFocusable(false);
        jScrollPane2.setViewportView(TextPlayers);

        jDesktopPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        TextMonsters.setEditable(false);
        TextMonsters.setColumns(20);
        TextMonsters.setRows(5);
        TextMonsters.setFocusable(false);
        jScrollPane4.setViewportView(TextMonsters);

        ActualLabel.setText("jLabel1");

        WinnerLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextLog, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CurrentPlayerLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(HaveAWinner)
                                        .addGap(42, 42, 42)
                                        .addComponent(WinnerLabel)))))
                        .addGap(18, 18, 18)
                        .addComponent(ActualLabel)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CurrentPlayerLabel)
                            .addComponent(ActualLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HaveAWinner)
                            .addComponent(WinnerLabel))
                        .addGap(68, 68, 68)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextLogActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new GraphicalUI().setVisible(true));
//    }
    
    @Override   
    public void showGame(GameState gameState) {   
        
        TextMonsters.setText(gameState.getMonsters());
        TextPlayers.setText(gameState.getPlayers());
        TextLog.setText(gameState.getLog());
        TextLabyrinth.setText(gameState.getLabyrinth());
        
        ActualLabel.setText(Integer.toString(gameState.getCurrentPlayer()));
        WinnerLabel.setText(Boolean.toString(gameState.isWinner()));
        
        repaint();
        
}

    @Override
    public Directions nextMove() {
        
        // Devuelve la dirección seleccionada por el usuario
        return this.cursors.getDirection();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ActualLabel;
    private javax.swing.JLabel CurrentPlayerLabel;
    private javax.swing.JLabel HaveAWinner;
    private javax.swing.JTextArea TextLabyrinth;
    private javax.swing.JTextField TextLog;
    private javax.swing.JTextArea TextMonsters;
    private javax.swing.JTextArea TextPlayers;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel WinnerLabel;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
